#!/bin/sh

# set the crush admin, if not setup
CRUSHADMIN=${CRUSHADMIN:-crushadmin}
CRUSHPASSWORD=${CRUSHPASSWORD:-crush9password}

# start the server
cd /var/opt/CrushFTP9_PC

if [ ! -d "/var/opt/CrushFTP9_PC/users/MainUsers/${CRUSHADMIN}" ]; then
    java -jar CrushFTP.jar -a "${CRUSHADMIN}" "${CRUSHPASSWORD}"
fi

sudo -u nobody java -jar CrushFTP.jar -d &

exit 0