#!/usr/bin/env bash

echo ""
echo "************************************************"
echo "CrushFTP is running"
echo "You should be able to access it on port 8080 or 9090 (unless you changed it)"
echo "CrushFTP admin username is '${CRUSHADMIN}'"
echo "************************************************"
echo ""

exit 0
